import { initializeApp } from "firebase/app";
import { Timestamp } from "firebase/firestore";
import {
  getFirestore,
  collection,
  addDoc,
  serverTimestamp,
} from "firebase/firestore";

const firebaseConfig = {
  apiKey: "YOUR_API_KEY",
  authDomain: "YOUR_AUTH_DOMAIN",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "YOUR_STORAGE_BUCKET",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID",
  measurementId: "YOUR_MEASUREMENT_ID", // Optional
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const jobs = [
  {
    postedOn: "2025-07-24",
    title: "Frontend Developer",
    company: "Google",
    type: "Full Time",
    experience: "Mid Level",
    location: "Bangalore",
    skills: ["React", "JavaScript", "HTML", "CSS"],
    job_link: "https://careers.google.com/jobs/results/",
  },
  {
    postedOn: "2025-07-23",
    title: "iOS Developer",
    company: "Apple",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["SwiftUI", "UIKit", "Core Data"],
    job_link: "https://www.apple.com/careers/in/",
  },
  {
    postedOn: "2025-07-22",
    title: "Backend Developer",
    company: "Microsoft",
    type: "Contract",
    experience: "Senior Level",
    location: "Hyderabad",
    skills: ["Node.js", "Express", "MongoDB"],
    job_link: "https://careers.microsoft.com/",
  },
  {
    postedOn: "2025-07-21",
    title: "UI/UX Designer",
    company: "Adobe",
    type: "Part Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["Figma", "Adobe XD", "User Research"],
    job_link: "https://www.adobe.com/careers.html",
  },
  {
    postedOn: "2025-07-20",
    title: "DevOps Engineer",
    company: "Amazon",
    type: "Full Time",
    experience: "Senior Level",
    location: "Pune",
    skills: ["AWS", "Docker", "Kubernetes"],
    job_link: "https://www.amazon.jobs/",
  },
  {
    postedOn: "2025-07-19",
    title: "Data Analyst",
    company: "Netflix",
    type: "Full Time",
    experience: "Entry Level",
    location: "Remote",
    skills: ["SQL", "Tableau", "Python"],
    job_link: "https://jobs.netflix.com/",
  },
  {
    postedOn: "2025-07-18",
    title: "Machine Learning Engineer",
    company: "Meta",
    type: "Full Time",
    experience: "Mid Level",
    location: "Bangalore",
    skills: ["Python", "TensorFlow", "PyTorch"],
    job_link: "https://www.metacareers.com/",
  },
  {
    postedOn: "2025-07-17",
    title: "Full Stack Developer",
    company: "TCS",
    type: "Full Time",
    experience: "Senior Level",
    location: "Chennai",
    skills: ["React", "Node.js", "SQL"],
    job_link: "https://www.tcs.com/careers",
  },
  {
    postedOn: "2025-07-16",
    title: "Product Manager",
    company: "Zomato",
    type: "Full Time",
    experience: "Mid Level",
    location: "Gurgaon",
    skills: ["Roadmapping", "Analytics", "Agile"],
    job_link: "https://www.zomato.com/careers",
  },
  {
    postedOn: "2025-07-15",
    title: "Graphic Designer",
    company: "Canva",
    type: "Part Time",
    experience: "Entry Level",
    location: "Remote",
    skills: ["Illustrator", "Photoshop", "Figma"],
    job_link: "https://www.canva.com/careers/",
  },
  {
    postedOn: "2025-07-14",
    title: "Business Analyst",
    company: "Infosys",
    type: "Full Time",
    experience: "Mid Level",
    location: "Pune",
    skills: ["Excel", "PowerBI", "SQL"],
    job_link: "https://www.infosys.com/careers.html",
  },
  {
    postedOn: "2025-07-13",
    title: "Data Engineer",
    company: "Swiggy",
    type: "Full Time",
    experience: "Senior Level",
    location: "Bangalore",
    skills: ["BigQuery", "Spark", "Python"],
    job_link: "https://careers.swiggy.com/",
  },
  {
    postedOn: "2025-07-12",
    title: "QA Engineer",
    company: "Paytm",
    type: "Full Time",
    experience: "Mid Level",
    location: "Noida",
    skills: ["Selenium", "Postman", "TestRail"],
    job_link: "https://paytm.com/about-us/opportunities/",
  },
  {
    postedOn: "2025-07-11",
    title: "Cloud Architect",
    company: "IBM",
    type: "Full Time",
    experience: "Senior Level",
    location: "Hyderabad",
    skills: ["Azure", "AWS", "DevOps"],
    job_link: "https://www.ibm.com/employment/",
  },
  {
    postedOn: "2025-07-10",
    title: "React Native Developer",
    company: "Ola",
    type: "Contract",
    experience: "Mid Level",
    location: "Remote",
    skills: ["React Native", "Redux", "APIs"],
    job_link: "https://www.olacabs.com/careers",
  },
  {
    postedOn: "2025-07-09",
    title: "WordPress Developer",
    company: "Wix",
    type: "Freelance",
    experience: "Mid Level",
    location: "Remote",
    skills: ["PHP", "WordPress", "WooCommerce"],
    job_link: "https://www.wix.com/jobs",
  },
  {
    postedOn: "2025-07-08",
    title: "Cyber Security Analyst",
    company: "Cisco",
    type: "Full Time",
    experience: "Mid Level",
    location: "Bangalore",
    skills: ["SIEM", "Firewalls", "Risk Analysis"],
    job_link: "https://jobs.cisco.com/",
  },
  {
    postedOn: "2025-07-07",
    title: "Tech Support Engineer",
    company: "Zoho",
    type: "Full Time",
    experience: "Entry Level",
    location: "Chennai",
    skills: ["Troubleshooting", "SQL", "Linux"],
    job_link: "https://www.zoho.com/careers.html",
  },
  {
    postedOn: "2025-07-06",
    title: "AI Researcher",
    company: "OpenAI",
    type: "Full Time",
    experience: "Senior Level",
    location: "Remote",
    skills: ["LLMs", "Python", "Machine Learning"],
    job_link: "https://openai.com/careers",
  },
  {
    postedOn: "2025-07-05",
    title: "Digital Marketing Specialist",
    company: "HubSpot",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["SEO", "Google Ads", "Content Marketing"],
    job_link: "https://www.hubspot.com/careers",
  },
  {
    postedOn: "2025-07-04",
    title: "Game Developer",
    company: "Ubisoft",
    type: "Full Time",
    experience: "Mid Level",
    location: "Pune",
    skills: ["Unity", "C#", "Game Design"],
    job_link: "https://www.ubisoft.com/en-us/company/careers",
  },
  {
    postedOn: "2025-07-03",
    title: "Blockchain Developer",
    company: "Coinbase",
    type: "Full Time",
    experience: "Senior Level",
    location: "Remote",
    skills: ["Solidity", "Web3.js", "Ethereum"],
    job_link: "https://www.coinbase.com/careers",
  },
  {
    postedOn: "2025-07-02",
    title: "Mobile App Tester",
    company: "Samsung",
    type: "Full Time",
    experience: "Entry Level",
    location: "Noida",
    skills: ["Android Testing", "Bug Tracking", "Test Cases"],
    job_link: "https://www.samsung.com/in/about-us/careers/",
  },
  {
    postedOn: "2025-07-01",
    title: "Technical Writer",
    company: "Atlassian",
    type: "Part Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["Documentation", "Markdown", "Git"],
    job_link: "https://www.atlassian.com/company/careers",
  },
  {
    postedOn: "2025-06-30",
    title: "System Administrator",
    company: "Wipro",
    type: "Full Time",
    experience: "Senior Level",
    location: "Bangalore",
    skills: ["Linux", "Windows Server", "Networking"],
    job_link: "https://careers.wipro.com/",
  },
];

export default jobs;

const addJobs = async () => {
  const jobsRef = collection(db, "jobs");
  for (const job of jobs) {
    await addDoc(jobsRef, {
      ...job,
      postedOn: Timestamp.fromDate(new Date(job.postedOn)),
    });
    console.log(` Job from ${job.company} added`);
  }
};
addJobs();
